/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lanchonete.view;

import com.lanchonete.classes.Produto;
import com.lanchonete.dao.ProdutoDao;
import com.lanchonete.db.Connect;
import com.lanchonete.model.ModelProdutoListagem;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 */
public class ListarProdutos extends javax.swing.JDialog {

    ProdutoDao daoProduto = new ProdutoDao();
    public ModelProdutoListagem modelProduto = new ModelProdutoListagem();
    Connect banco = new Connect();

    public ListarProdutos(java.awt.Window parent) {
        super(parent);
        setModal(true);
        initComponents();
        carregaProdutos(daoProduto.list());

        setLocationRelativeTo(null);
    }

    public void carregaProdutos(List<Produto> lista) {
        modelProduto.setData(lista);
        jTableProdutos.setModel(modelProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jBConsultar = new javax.swing.JButton();
        jTCdPedido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Produtos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableProdutosKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProdutos);

        jBConsultar.setMnemonic('C');
        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jBConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBConsultarKeyPressed(evt);
            }
        });

        jTCdPedido.setToolTipText("Código do Cliente");
        jTCdPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produto"));
        jTCdPedido.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTCdPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTCdPedidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTCdPedidoFocusLost(evt);
            }
        });
        jTCdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCdPedidoActionPerformed(evt);
            }
        });
        jTCdPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCdPedidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCdPedidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTCdPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTCdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProdutosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProdutosKeyPressed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        if (jTCdPedido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira um Nome Válido");
            return;
        }
        carregaProdutos(daoProduto.findByName(jTCdPedido.getText()));
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBConsultarKeyPressed

    }//GEN-LAST:event_jBConsultarKeyPressed

    private void jTCdPedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCdPedidoFocusGained

    }//GEN-LAST:event_jTCdPedidoFocusGained

    private void jTCdPedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTCdPedidoFocusLost

    }//GEN-LAST:event_jTCdPedidoFocusLost

    private void jTCdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCdPedidoActionPerformed

    private void jTCdPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCdPedidoKeyPressed

    }//GEN-LAST:event_jTCdPedidoKeyPressed

    private void jTCdPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCdPedidoKeyTyped

    }//GEN-LAST:event_jTCdPedidoKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTCdPedido;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
